name: Generate LeetCode Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Anurag915
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/github-snake.svg assets/github-snake-dark.svg
          git commit -m "Updated snake contribution graph"
          git push
