name: Generate LeetCode Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-streak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch LeetCode Streak Data
        run: |
          curl -X POST https://leetcode.com/graphql/ \
          -H "Content-Type: application/json" \
          --data '{"query":"query { matchedUser(username: \"anurag1cr\") { submitStatsGlobal { streakCounter } } }"}' \
          | jq '.data.matchedUser.submitStatsGlobal.streakCounter' > streak.txt

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add streak.txt
          git commit -m "Updated LeetCode streak"
          git push
